### ISSUE TITLE
EOS authority joining node

### ISSUE THREAD

**Issue by eosauthority** [eosjapan/eosjapan-testnet#1]
Server location: London
Producer name: eosauthority
IP/DOMAIN: 888 (HTTP) 9807 (p2p)
Your public key: EOS6hvPyMu7wybVi1S6hAoknwyeCX3EPDx8EribnJiET4awdmzbQD

Node is synced.

**Comment by newbdez33** [comment]
Hi Thanks, 
But can you pick a producer name from this list:
http://www.samurai-goldfish.net

I will put your org name as "EOS Authority" on status monitor page this weekend.

**Comment by eosauthority** [comment]
Thanks. I was not sure if a particular name was taken. See below

Server location: London
Producer name: comet
IP/DOMAIN: 888 (HTTP) 9807 (p2p)
Your public key: EOS6hvPyMu7wybVi1S6hAoknwyeCX3EPDx8EribnJiET4awdmzbQD

**Comment by newbdez33** [comment]
Done.
I can see your node is producing well :)

Welcome and Cheers!

**Comment by eosauthority** [comment]
Great. I can see on the logs as well. Good work.
